version: '3.8'

services:
  mongo:
    image: mongo:6
    restart: always
    container_name: yaqeen-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: yaqeen-backend
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: yaqeen-frontend
    restart: always
    ports:
      - "3000:80"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend

volumes:
  mongo_data: